<?php

namespace app\models;

use yii\base\Model;
use yii\data\ActiveDataProvider;
use app\models\Information_of_directory;

/**
 * Information_of_directorySearch represents the model behind the search form of `app\models\Information_of_directory`.
 */
class Information_of_directorySearch extends Information_of_directory
{
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'id_directory', 'id_shop', 'id_product', 'count', 'deleted'], 'integer'],
            [['price_for_one'], 'number'],
        ];
    }

    public static function tableName()
    {
        return 'information_of_directory'; // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $query = Information_of_directory::find()->where(['deleted'=>0]);

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        // grid filtering conditions
        $query->andFilterWhere([
            'id' => $this->id,
            'id_directory' => $this->id_directory,
            'id_shop' => $this->id_shop,
            'id_product' => $this->id_product,
            'price_for_one' => $this->price_for_one,
            'count' => $this->count,
            'deleted' => $this->deleted,
        ]);

        return $dataProvider;
    }
}
