<?php

namespace app\models;

use yii\base\Model;
use yii\data\ActiveDataProvider;
use app\models\Order_of_Route;

/**
 * Order_of_RouteSearch represents the model behind the search form of `app\models\Order_of_Route`.
 */
class Order_of_RouteSearch extends Order_of_Route
{
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'id_route', 'id_shop', 'NPP', 'deleted'], 'integer'],
        ];
    }

    public static function tableName()
    {
        return 'order_of_route'; // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $query = Order_of_Route::find()->where(['deleted'=>0]);

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query->orderBy(['NPP'=> SORT_ASC]),
        ]);

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        // grid filtering conditions
        $query->andFilterWhere([
            'id' => $this->id,
            'id_route' => $this->id_route,
            'id_shop' => $this->id_shop,
            'NPP' => $this->NPP,
            'deleted' => $this->deleted,
        ]);

        return $dataProvider;
    }
}
