<?php

namespace app\models;

use yii\base\Model;
use yii\data\ActiveDataProvider;
use app\models\Products_for_entity;

/**
 * Products_for_entitySearch represents the model behind the search form of `app\models\Products_for_entity`.
 */
class Products_for_entitySearch extends Products_for_entity
{
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'id_entity', 'id_product', 'deleted'], 'integer'],
            [['price'], 'number'],
        ];
    }
    public static function tableName()
    {
        return 'products_for_entity'; // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function scenarios()
    {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    /**
     * Creates data provider instance with search query applied
     *
     * @param array $params
     *
     * @return ActiveDataProvider
     */
    public function search($params)
    {
        $query = Products_for_entity::find()->where(['deleted'=>0]);

        // add conditions that should always apply here

        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        $this->load($params);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        // grid filtering conditions
        $query->andFilterWhere([
            'id' => $this->id,
            'id_entity' => $this->id_entity,
            'id_product' => $this->id_product,
            'price' => $this->price,
            'deleted' => $this->deleted,
        ]);

        return $dataProvider;
    }
}
